### ISSUE TITLE
Problem with creating wheels 

### ISSUE THREAD

**Issue by JensZander** [w9cf/cwsim#1]
Hi Kevin.
Super nice implementation, thanks a million for sharing!
I am a casual Python user (no package-wiz :) ) and had some minor issues with installing it on my Mac (BigSur 11.7), Python 3.11.
Running pip with the requirements file went fine until the final build of wheels for numpy, matplotlib where the installation crashed. (some output argument was no of the proper type - sounds like some compatibilty problem).  When a ran "pip install" manually line by line in requirements.txt everything worked just fine.  cwsim is running like a charm!

/Jens  SM0HEV/SM1HEV/SF1Z  CWops #2237

**Comment by w9cf** [comment]
I changed the requirements.txt and requirements_qt5.txt to use >= instead of ==. I think this should allow pip to use a later version with prebuilt wheels which I think should work. If not, please reopen the issue.
